# Site settings
title: TrackIt
description: >
  Time is equally given to everyone, but how you use it can make all the difference. This app is more than just a time tracker. It’s a powerful companion that helps you stay focused on your goals, see the results of your efforts at a glance, and measure your progress effectively.

tags: "trackit, timetracker, timetrackingapp, pomodoro, tasktracker"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://teamtrackit.github.io/" # the base hostname & protocol for your site

author:
  fullname: TrackIt
  github: https://teamtrackit.github.io/
  contact: https://tracktogoal.canny.io/feature-requests


# Syntax highlighting
highlightstyle: 'agate'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]


# Build settings
highlighter: null
markdown: kramdown
